### ISSUE TITLE
[Improvement] Use build options instead of config file

### ISSUE THREAD

**Issue by anirudhjain75** [justwriteclick/versions-jekyll#21]
Hi, After reading the script used to build the versions. Here is a tip. 

https://jekyllrb.com/docs/configuration/options/#build-command-options In build command options, Why not use the -b flag instead ?

This way we can move from having to create multiple config files.

**Comment by anirudhjain75** [comment]
@annegentle

**Comment by annegentle** [comment]
I think it could be done either way. By encoding `baseurl` in the _config.yml and `_config.4.1.1.yml` and so on files, the branches can continue to have those config files so you know precisely what the build used in the past, rather than having to look through logs to see what was passed to the `-b` parameter at build time. Probably six of one, half a dozen of the other.
